### ISSUE TITLE
Node Sass binding

### ISSUE THREAD

**Issue by dkh215** [bahmutov/cypress-vue-unit-test#18]
Using Version 1.10.0

I'm using Sass in a single file component and am encountering the error below:

```
Node Sass could not find a binding for your current environment: OS X 64-bit with Electron 1.4.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 9.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
```

I tried running `npm rebuild node-sass --force` but the error persists. 

 I'm including my webpack config as instructed in the README and have node-sass: 
`on('file:preprocessor', onFilePreprocessor('/path/to/webpack/config'))`

**Comment by amirrustam** [comment]
@dkh215 I don't believe this to be a `cypress-vue-unit-test` issue, but can please you share your Webpack config?

**Comment by bahmutov** [comment]
Hmm, this could be a difference in Node loading sass vs Cypress (Electron) loading it. Damn node-sass. Need to have separate example repo to test it.

**Comment by amirrustam** [comment]
@bahmutov interesting 🤔

@dkh215 what version of Cypress are you running?

**Comment by amirrustam** [comment]
I was able to reproduce this issue. Here is the repo: [amirrustam/cypress-vue-unit-issue-18-repo](https://github.com/amirrustam/cypress-vue-unit-issue-18-repo)

<img width="1414" alt="node-sass-issue-18" src="https://user-images.githubusercontent.com/334337/35878354-e7bd9df0-0b2c-11e8-8852-59c42c7f89c7.png">

I'm running the similar environment as you @dkh215. Though I'm using version v1.10.1 and Cypress v1.4.2. 

I'm looking further into this.

**Comment by leRenart** [comment]
Any update about this issue ?

**Comment by bahmutov** [comment]
Sorry did not have time to look into this

**Comment by leRenart** [comment]
I can confirm that with node 8.x.x it works as expected

**Comment by brian-mann** [comment]
We likely need to rebuild the native `node-sass` prior to distributing Cypress - as it comes prepacked with native binaries.

**Comment by brian-mann** [comment]
I think I know what the problem is - we build OSX + Windows version of Cypress in each applicable operating system.

In those builds - we forgot the bump the locally installed node version. So what's happening is that Cypress is using node `6.x.x` to install and build native node modules (node-sass) and then it's build the Cypress binary and then uploading it with those node modules.

Linux is correct - because we did bump the node version there.

As long as we bump Windows + OSX node version when distributing Cypress binaries everything "will just work".

We'll need to release `2.0.5` with this fix. As long as Cypress itself distributes the binaries natively compiled against its node version everything will always work. So it's actually a benefit to distributing node as opposed to using system node.

When we originally released version `2.0.0` we bumped Electron which also bumped node to `8.x.x` and this is where the problem was introduced.

**Comment by Sjeiti** [comment]
Having similar issues on Windows running Cypress 2.1.0 (and Node 8.1.3).
I get this error:
```
  ./node_modules/css-loader!./node_modules/vue-loader/lib/style-compiler?{"optionsId":"0","vue":true,"id":"data-v-1260502b","scoped":true,"sourceMap":false}!./node_modules/sass-loader/lib/loader.js!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/components/Footer.vue
  Module build failed: Error: A dynamic link library (DLL) initialization routine failed.
  \\?\C:\Users\micro\projects\project-invoice\node_modules\node-sass\vendor\win32-x64-57\binding.node
   @ ./node_modules/vue-style-loader!./node_modules/css-loader!./node_modules/vue-loader/lib/style-compiler?{"optionsId":"0","vue":true,"id":"data-v-1260502b","scoped":true,"sourceMap":false}!./node_modules/sass-loader/lib/loader.js!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/components/Footer.vue 4:14-345
   @ ./src/components/Footer.vue
   @ ./cypress/integration/unit/components/Footer.spec.js
```

From the last comment on the reference above I gather that the issue should be fixed in Cypress 2.1.0. So is my error something else?

**Comment by phao5814** [comment]
I'm also having this exact issue on macOS. I'm using v9.2.0 of Node and v1.1.3 of @cypress/webpack-preprocessor since I'm using Webpack v3.6.0. I'm bundling the long way [per the docs here](https://github.com/bahmutov/cypress-vue-unit-test).

The error I receive when trying to mount my vue component is as follows:

```
./node_modules/css-loader!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-30a2f442","scoped":true,"hasInlineConfig":false}!./node_modules/sass-loader/lib/loader.js!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/components/dashboard/dashCardMap.vue
Module build failed: Error: Missing binding /folder/to/node_modules/node-sass/vendor/darwin-x64-57/binding.node
Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 8.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 9.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
```

Running `npm rebuild node-sass --force` unfortunately doesn't solve the problem. Any ideas on how I can resolve this?

**Comment by JimBacon** [comment]
I am also still experiencing this problem. It is my understanding that the resolution proposed by @brian-mann assumes that Cypress will employ a version of node-sass that has been built for and distributed with it. In practice, what I observe is that Cypress uses my local copy. (This is on Windows.)

If I use Node v > 8 then I get an error like @phao5814. 

If I use Node v8 then the error I get is like @Sjeiti (i.e. when my version of Node matches that of Cypress). 

After going round many houses I finally realise that "only 32bit binaries are provided for Windows". If I change to Node v8 32-bit and re-install node-sass my error now reads
```
Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 8.x

Found bindings for the following environments:
  - Windows 32-bit with Node.js 8.x

```
So I'm stuck because Cypress isn't using its own version of node-sass and I can't provide it with the version that it needs.

Is there a way the my webpack config can persuade Cypress to get node-sass from its own installation files? What path would I have to provide? I haven't been able to find it.

**Comment by gleb-britecore** [comment]
I managed to fix this by overriding nodeVersion in settings:
`  "nodeVersion": "system",`

https://docs.cypress.io/guides/references/configuration.html#Node-version

You can verify it in Cypress preferences window
![image](https://user-images.githubusercontent.com/29545691/71531071-b2cb7c00-28f5-11ea-9a8a-636d2f96bce2.png)

**Comment by amirrustam** [comment]
Thanks for providing your comment here @gleb-britecore. Allowing you to use your system's Node version was one of the improvements we rolled out in v3.5: https://cypress.io/blog/2019/11/05/cypress-3-5-and-3-6-release/#useryoursystemsnode

Closing for now, but feel free to re-open.
